extends Node2D

export(PackedScene) var message

onready var follow = get_node("Path2D")
export (PackedScene) var Enemy_01
export (PackedScene) var Enemy_02
export (PackedScene) var Enemy_03
var Enemy_04 = load("res://Scenes/Enemy04.tscn")

var enemigo
var cant_enemy = 0
var timer = 0
var oleada_numero = 0

func _ready():
	$Music.play()

func _process(delta):
		
	if cant_enemy==0:
		if oleada_numero < 11:
			oleada_numero += 1
			timer = 0
		if oleada_numero == 1:
			cant_enemy = 8
		if oleada_numero == 2:
			cant_enemy = 15
			$GUI/Score.text =str( float($GUI/Score.text )+ 100)
		if oleada_numero == 3:
			cant_enemy = 33
			$GUI/Score.text =str( float($GUI/Score.text )+ 200)
		if oleada_numero == 4:
			cant_enemy = 33
			$GUI/Score.text =str( float($GUI/Score.text )+ 400)
		if oleada_numero == 5:
			cant_enemy = 43
			$GUI/Score.text =str( float($GUI/Score.text )+ 500)
		if oleada_numero == 6:
			cant_enemy = 60
			$GUI/Score.text =str( float($GUI/Score.text )+ 600)
		if oleada_numero == 7:
			cant_enemy = 70
			$GUI/Score.text =str( float($GUI/Score.text )+ 700)
		if oleada_numero == 8:
			cant_enemy = 80
			$GUI/Score.text =str( float($GUI/Score.text )+ 800)
		if oleada_numero == 9:
			cant_enemy = 90
			$GUI/Score.text =str( float($GUI/Score.text )+ 900)
		if oleada_numero == 10:
			cant_enemy = 92
			$GUI/Score.text =str( float($GUI/Score.text )+ 1000)
	
		
	if oleada_numero == 1 :
		oleada_01()
	if oleada_numero == 2 :
		oleada_02()
	if oleada_numero == 3 :
		oleada_03()
	if oleada_numero == 4 :
		oleada_04()
	if oleada_numero == 5 :
		oleada_05()
	if oleada_numero == 6 :
		oleada_06()
	if oleada_numero == 7 :
		oleada_07()
	if oleada_numero == 8 :
		oleada_08()
	if oleada_numero == 9 :
		oleada_09()
	if oleada_numero == 10 :
		oleada_10()
	if oleada_numero == 11 :
		oleada_11()
	pass


func _nuevo_enemigo(name,escudo):
	name = Enemy_01.instance()
	name.get_node("Path2D").curve = follow.curve 
	if escudo:
		name.escudo = true
	else:
		name.escudo = false
	add_child (name)
	
func _nuevo_enemigo2(name):
	name = Enemy_02.instance()
	name.get_node("Path2D").curve = follow.curve 
	add_child (name)
	
func _nuevo_enemigo3(name):
	name = Enemy_03.instance()
	name.get_node("Path2D").curve = follow.curve 
	add_child (name)

func _nuevo_enemigo4(name):
	name = Enemy_04.instance()
	name.get_node("Path2D").curve = follow.curve 
	add_child (name)
	
func oleada_01():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_01.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,false)
	if timer == 350: _nuevo_enemigo(enemigo,false)
	if timer == 650: _nuevo_enemigo(enemigo,false)
	if timer == 900: _nuevo_enemigo(enemigo,false)
	if timer == 1250: _nuevo_enemigo(enemigo,false)
	if timer == 1450: _nuevo_enemigo(enemigo,false)
	if timer == 1650: _nuevo_enemigo(enemigo,false)
	if timer == 1800: _nuevo_enemigo(enemigo,false)
		
func oleada_02():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_02.png")
			get_parent().add_child(message_instance)
			
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,false)
	if timer == 720: _nuevo_enemigo(enemigo,false)
	if timer == 820: _nuevo_enemigo(enemigo,false)
	if timer == 900: _nuevo_enemigo(enemigo,false)
	if timer == 1100: _nuevo_enemigo(enemigo,false)
	if timer == 1250: _nuevo_enemigo(enemigo,false)
	if timer == 1350: _nuevo_enemigo(enemigo,false)
	if timer == 1420: _nuevo_enemigo(enemigo,false)
	if timer == 1500: _nuevo_enemigo(enemigo,false)
	if timer == 1620: _nuevo_enemigo(enemigo,false)
	if timer == 1800: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,true)
	if timer == 2200: _nuevo_enemigo2(enemigo)
	
		
func oleada_03():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_03.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,false)
	if timer == 1250: _nuevo_enemigo(enemigo,false)
	if timer == 1500: _nuevo_enemigo(enemigo,false)
	if timer == 1600: _nuevo_enemigo(enemigo,false)
	if timer == 1650: _nuevo_enemigo(enemigo,false)
	if timer == 1800: _nuevo_enemigo(enemigo,false)
	if timer == 1870: _nuevo_enemigo(enemigo,false)
	if timer == 1920: _nuevo_enemigo(enemigo,false)
	if timer == 2000: _nuevo_enemigo(enemigo,false)
	if timer == 2050: _nuevo_enemigo(enemigo,false)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,true)
	if timer == 2200: _nuevo_enemigo(enemigo,false)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,false)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,false)
	if timer == 3000: _nuevo_enemigo(enemigo,false)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,false)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,false)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,false)
	if timer == 3920: _nuevo_enemigo(enemigo,false)
	if timer == 4000: _nuevo_enemigo(enemigo,true)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	
func oleada_04():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_04.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,false)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,false)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,false)
	if timer == 1870: _nuevo_enemigo(enemigo,false)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,false)
	if timer == 2050: _nuevo_enemigo(enemigo,false)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,false)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,false)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)

func oleada_05():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_05.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,false)
	if timer == 1870: _nuevo_enemigo(enemigo,false)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,false)
	if timer == 2050: _nuevo_enemigo(enemigo,false)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo(enemigo,false)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,false)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo2(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)

func oleada_06():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_06.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,false)
	if timer == 1870: _nuevo_enemigo(enemigo,false)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,false)
	if timer == 2050: _nuevo_enemigo(enemigo,false)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo3(enemigo)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,false)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo3(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)
	if timer == 5350: _nuevo_enemigo(enemigo,false)
	if timer == 5420: _nuevo_enemigo(enemigo,true)
	if timer == 5500: _nuevo_enemigo(enemigo,false)
	if timer == 5650: _nuevo_enemigo(enemigo,false)
	if timer == 5800: _nuevo_enemigo(enemigo,true)
	if timer == 6000: _nuevo_enemigo(enemigo,true)
	if timer == 6200: _nuevo_enemigo(enemigo,false)
	if timer == 6350: _nuevo_enemigo(enemigo,true)
	if timer == 6420: _nuevo_enemigo(enemigo,false)
	if timer == 6600: _nuevo_enemigo(enemigo,true)
	if timer == 6650: _nuevo_enemigo(enemigo,false)
	if timer == 6800: _nuevo_enemigo(enemigo,true)
	if timer == 6870: _nuevo_enemigo(enemigo,true)
	if timer == 6920: _nuevo_enemigo(enemigo,true)
	if timer == 7000: _nuevo_enemigo2(enemigo)
	if timer == 7100: _nuevo_enemigo2(enemigo)
	if timer == 7200: _nuevo_enemigo3(enemigo)

func oleada_07():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_07.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 250: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 450: _nuevo_enemigo(enemigo,true)
	if timer == 550: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,true)
	if timer == 1870: _nuevo_enemigo(enemigo,true)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,true)
	if timer == 2050: _nuevo_enemigo(enemigo,true)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo3(enemigo)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,true)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo3(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)
	if timer == 5350: _nuevo_enemigo(enemigo,false)
	if timer == 5420: _nuevo_enemigo(enemigo,true)
	if timer == 5500: _nuevo_enemigo(enemigo,false)
	if timer == 5650: _nuevo_enemigo(enemigo,false)
	if timer == 5800: _nuevo_enemigo(enemigo,true)
	if timer == 6000: _nuevo_enemigo(enemigo,true)
	if timer == 6200: _nuevo_enemigo(enemigo,false)
	if timer == 6350: _nuevo_enemigo(enemigo,true)
	if timer == 6420: _nuevo_enemigo(enemigo,false)
	if timer == 6600: _nuevo_enemigo(enemigo,true)
	if timer == 6650: _nuevo_enemigo(enemigo,false)
	if timer == 6800: _nuevo_enemigo(enemigo,true)
	if timer == 6870: _nuevo_enemigo(enemigo,true)
	if timer == 6920: _nuevo_enemigo(enemigo,true)
	if timer == 7000: _nuevo_enemigo3(enemigo)
	if timer == 7100: _nuevo_enemigo2(enemigo)
	if timer == 7300: _nuevo_enemigo3(enemigo)
	if timer == 7400: _nuevo_enemigo2(enemigo)
	if timer == 7500: _nuevo_enemigo2(enemigo)
	if timer == 7650: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7900: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 8200: _nuevo_enemigo3(enemigo)

func oleada_08():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_08.png")
			get_parent().add_child(message_instance)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 250: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 450: _nuevo_enemigo(enemigo,true)
	if timer == 550: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,true)
	if timer == 1870: _nuevo_enemigo(enemigo,true)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,true)
	if timer == 2050: _nuevo_enemigo(enemigo,true)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo3(enemigo)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,true)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo3(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)
	if timer == 5350: _nuevo_enemigo(enemigo,false)
	if timer == 5420: _nuevo_enemigo(enemigo,true)
	if timer == 5500: _nuevo_enemigo(enemigo,false)
	if timer == 5650: _nuevo_enemigo(enemigo,false)
	if timer == 5800: _nuevo_enemigo(enemigo,true)
	if timer == 6000: _nuevo_enemigo(enemigo,true)
	if timer == 6200: _nuevo_enemigo(enemigo,false)
	if timer == 6350: _nuevo_enemigo(enemigo,true)
	if timer == 6420: _nuevo_enemigo(enemigo,false)
	if timer == 6600: _nuevo_enemigo(enemigo,true)
	if timer == 6650: _nuevo_enemigo(enemigo,false)
	if timer == 6800: _nuevo_enemigo(enemigo,true)
	if timer == 6870: _nuevo_enemigo(enemigo,true)
	if timer == 6920: _nuevo_enemigo(enemigo,true)
	if timer == 7000: _nuevo_enemigo3(enemigo)
	if timer == 7100: _nuevo_enemigo2(enemigo)
	if timer == 7300: _nuevo_enemigo3(enemigo)
	if timer == 7400: _nuevo_enemigo2(enemigo)
	if timer == 7500: _nuevo_enemigo2(enemigo)
	if timer == 7650: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7900: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 8200: _nuevo_enemigo3(enemigo)
	if timer == 8400: _nuevo_enemigo3(enemigo)
	if timer == 8550: _nuevo_enemigo2(enemigo)
	if timer == 8700: _nuevo_enemigo3(enemigo)
	if timer == 8950: _nuevo_enemigo2(enemigo)
	if timer == 9100: _nuevo_enemigo2(enemigo)
	if timer == 9250: _nuevo_enemigo2(enemigo)
	if timer == 9300: _nuevo_enemigo2(enemigo)
	if timer == 9450: _nuevo_enemigo2(enemigo)
	if timer == 9600: _nuevo_enemigo3(enemigo)
	if timer == 9700: _nuevo_enemigo4(enemigo)
	
func oleada_09():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_09.png")
			get_parent().add_child(message_instance)
	if timer == 100: _nuevo_enemigo3(enemigo)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 250: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 450: _nuevo_enemigo(enemigo,true)
	if timer == 550: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,true)
	if timer == 1870: _nuevo_enemigo(enemigo,true)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,true)
	if timer == 2050: _nuevo_enemigo(enemigo,true)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 2900: _nuevo_enemigo3(enemigo)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3100: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo3(enemigo)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,true)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo4(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)
	if timer == 5350: _nuevo_enemigo(enemigo,false)
	if timer == 5420: _nuevo_enemigo(enemigo,true)
	if timer == 5500: _nuevo_enemigo(enemigo,false)
	if timer == 5650: _nuevo_enemigo(enemigo,false)
	if timer == 5800: _nuevo_enemigo(enemigo,true)
	if timer == 6000: _nuevo_enemigo(enemigo,true)
	if timer == 6100: _nuevo_enemigo3(enemigo)
	if timer == 6200: _nuevo_enemigo(enemigo,false)
	if timer == 6350: _nuevo_enemigo(enemigo,true)
	if timer == 6420: _nuevo_enemigo(enemigo,false)
	if timer == 6600: _nuevo_enemigo(enemigo,true)
	if timer == 6650: _nuevo_enemigo(enemigo,false)
	if timer == 6800: _nuevo_enemigo(enemigo,true)
	if timer == 6870: _nuevo_enemigo(enemigo,true)
	if timer == 6920: _nuevo_enemigo(enemigo,true)
	if timer == 7000: _nuevo_enemigo3(enemigo)
	if timer == 7100: _nuevo_enemigo2(enemigo)
	if timer == 7300: _nuevo_enemigo3(enemigo)
	if timer == 7350: _nuevo_enemigo(enemigo,true)
	if timer == 7400: _nuevo_enemigo2(enemigo)
	if timer == 7500: _nuevo_enemigo2(enemigo)
	if timer == 7650: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7850: _nuevo_enemigo(enemigo,true)
	if timer == 7900: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7900: _nuevo_enemigo(enemigo,true)
	if timer == 8000: _nuevo_enemigo(enemigo,true)
	if timer == 8100: _nuevo_enemigo(enemigo,true)
	if timer == 8200: _nuevo_enemigo3(enemigo)
	if timer == 8400: _nuevo_enemigo3(enemigo)
	if timer == 8550: _nuevo_enemigo2(enemigo)
	if timer == 8700: _nuevo_enemigo3(enemigo)
	if timer == 8950: _nuevo_enemigo2(enemigo)
	if timer == 9100: _nuevo_enemigo2(enemigo)
	if timer == 9250: _nuevo_enemigo2(enemigo)
	if timer == 9300: _nuevo_enemigo2(enemigo)
	if timer == 9450: _nuevo_enemigo2(enemigo)
	if timer == 9600: _nuevo_enemigo3(enemigo)
	if timer == 9650: _nuevo_enemigo(enemigo,true)
	if timer == 9700: _nuevo_enemigo4(enemigo)
	

func oleada_10():
	timer += 1
	if timer == 1:
		if $Adentro_base.energy_base > 0:
			var message_instance = message.instance()
			message_instance.get_node("Spr_message").texture = load("res://Art/wave_10.png")
			get_parent().add_child(message_instance)
	if timer == 100: _nuevo_enemigo3(enemigo)
	if timer == 150: _nuevo_enemigo(enemigo,true)
	if timer == 250: _nuevo_enemigo(enemigo,true)
	if timer == 350: _nuevo_enemigo(enemigo,true)
	if timer == 450: _nuevo_enemigo(enemigo,true)
	if timer == 550: _nuevo_enemigo(enemigo,true)
	if timer == 650: _nuevo_enemigo(enemigo,true)
	if timer == 900: _nuevo_enemigo(enemigo,true)
	if timer == 1250: _nuevo_enemigo(enemigo,true)
	if timer == 1500: _nuevo_enemigo(enemigo,true)
	if timer == 1600: _nuevo_enemigo(enemigo,true)
	if timer == 1650: _nuevo_enemigo(enemigo,true)
	if timer == 1800: _nuevo_enemigo(enemigo,true)
	if timer == 1870: _nuevo_enemigo(enemigo,true)
	if timer == 1920: _nuevo_enemigo(enemigo,true)
	if timer == 2000: _nuevo_enemigo(enemigo,true)
	if timer == 2050: _nuevo_enemigo(enemigo,true)
	if timer == 2100: _nuevo_enemigo(enemigo,true)
	if timer == 2130: _nuevo_enemigo(enemigo,false)
	if timer == 2200: _nuevo_enemigo(enemigo,true)
	if timer == 2350: _nuevo_enemigo(enemigo,false)
	if timer == 2420: _nuevo_enemigo(enemigo,true)
	if timer == 2500: _nuevo_enemigo(enemigo,false)
	if timer == 2650: _nuevo_enemigo(enemigo,false)
	if timer == 2800: _nuevo_enemigo(enemigo,true)
	if timer == 2900: _nuevo_enemigo3(enemigo)
	if timer == 3000: _nuevo_enemigo(enemigo,true)
	if timer == 3100: _nuevo_enemigo(enemigo,true)
	if timer == 3200: _nuevo_enemigo(enemigo,false)
	if timer == 3350: _nuevo_enemigo(enemigo,true)
	if timer == 3420: _nuevo_enemigo(enemigo,false)
	if timer == 3600: _nuevo_enemigo(enemigo,true)
	if timer == 3650: _nuevo_enemigo(enemigo,false)
	if timer == 3800: _nuevo_enemigo(enemigo,true)
	if timer == 3870: _nuevo_enemigo(enemigo,true)
	if timer == 3920: _nuevo_enemigo(enemigo,true)
	if timer == 4000: _nuevo_enemigo2(enemigo)
	if timer == 4100: _nuevo_enemigo2(enemigo)
	if timer == 4200: _nuevo_enemigo2(enemigo)
	if timer == 4350: _nuevo_enemigo(enemigo,true)
	if timer == 4420: _nuevo_enemigo3(enemigo)
	if timer == 4600: _nuevo_enemigo(enemigo,true)
	if timer == 4650: _nuevo_enemigo(enemigo,true)
	if timer == 4800: _nuevo_enemigo(enemigo,true)
	if timer == 4870: _nuevo_enemigo(enemigo,true)
	if timer == 4920: _nuevo_enemigo(enemigo,true)
	if timer == 5000: _nuevo_enemigo2(enemigo)
	if timer == 5100: _nuevo_enemigo4(enemigo)
	if timer == 5200: _nuevo_enemigo2(enemigo)
	if timer == 5350: _nuevo_enemigo(enemigo,false)
	if timer == 5420: _nuevo_enemigo(enemigo,true)
	if timer == 5500: _nuevo_enemigo(enemigo,false)
	if timer == 5650: _nuevo_enemigo(enemigo,false)
	if timer == 5800: _nuevo_enemigo(enemigo,true)
	if timer == 6000: _nuevo_enemigo(enemigo,true)
	if timer == 6100: _nuevo_enemigo3(enemigo)
	if timer == 6200: _nuevo_enemigo(enemigo,false)
	if timer == 6350: _nuevo_enemigo(enemigo,true)
	if timer == 6420: _nuevo_enemigo(enemigo,false)
	if timer == 6600: _nuevo_enemigo(enemigo,true)
	if timer == 6650: _nuevo_enemigo(enemigo,false)
	if timer == 6800: _nuevo_enemigo(enemigo,true)
	if timer == 6870: _nuevo_enemigo(enemigo,true)
	if timer == 6920: _nuevo_enemigo(enemigo,true)
	if timer == 7000: _nuevo_enemigo3(enemigo)
	if timer == 7100: _nuevo_enemigo2(enemigo)
	if timer == 7300: _nuevo_enemigo3(enemigo)
	if timer == 7350: _nuevo_enemigo(enemigo,true)
	if timer == 7400: _nuevo_enemigo2(enemigo)
	if timer == 7500: _nuevo_enemigo2(enemigo)
	if timer == 7650: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7850: _nuevo_enemigo(enemigo,true)
	if timer == 7900: _nuevo_enemigo2(enemigo)
	if timer == 7800: _nuevo_enemigo2(enemigo)
	if timer == 7900: _nuevo_enemigo(enemigo,true)
	if timer == 8000: _nuevo_enemigo(enemigo,true)
	if timer == 8100: _nuevo_enemigo(enemigo,true)
	if timer == 8200: _nuevo_enemigo3(enemigo)
	if timer == 8400: _nuevo_enemigo3(enemigo)
	if timer == 8550: _nuevo_enemigo2(enemigo)
	if timer == 8700: _nuevo_enemigo3(enemigo)
	if timer == 8950: _nuevo_enemigo2(enemigo)
	if timer == 9100: _nuevo_enemigo2(enemigo)
	if timer == 9250: _nuevo_enemigo2(enemigo)
	if timer == 9300: _nuevo_enemigo2(enemigo)
	if timer == 9450: _nuevo_enemigo2(enemigo)
	if timer == 9600: _nuevo_enemigo3(enemigo)
	if timer == 9650: _nuevo_enemigo(enemigo,true)
	if timer == 9700: _nuevo_enemigo4(enemigo)
	if timer == 9800: _nuevo_enemigo4(enemigo)
	if timer == 9900: _nuevo_enemigo4(enemigo)
	
func oleada_11():
	timer += 1
	if timer == 1:
		var message_instance = message.instance()
		message_instance.get_node("Spr_message").texture = load("res://Art/safe.png")
		get_parent().add_child(message_instance)
	
	if timer == 300: get_tree().change_scene("res://Scenes/Game.tscn")